services:
  - type: web
    name: springai-recipe-backend
    runtime: java21             # <--- MODIFIED TO BE MORE SPECIFIC
    region: oregon
    branch: main
    plan: free
    buildFilter:
      paths:
        - "src/**"
        - "pom.xml"
        - "system.properties"
        - ".mvn/**"
        - "mvnw"
        - "mvnw.cmd"
        - "render.yaml"
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/SpringAIProject-0.0.1-SNAPSHOT.jar" # Adjust JAR name!
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      # - key: SPRING_PROFILES_ACTIVE
      #   value: production